### ISSUE TITLE
always exit on height=817983 with ChainError 

### ISSUE THREAD

**Issue by AI-Chef** [atomicals/atomicals-electrumx#14]
here is the log
```
electrumx  | INFO:BlockProcessor:advance_txs: color_atomicals_outputs atomical_ids_transferred. atomical_id=75855c1d2ebdc253c47b13c3ad4a334d77fbf09b36f7f4f8193e287f5e4715ab00000000, tx_hash=fe1949053ea0021b1ac14a6e4646987bf474750fd01e382fa5835b62a4c30b4c
electrumx  | INFO:BlockProcessor:advance_txs: has_at_least_one_valid_atomicals_operation tx_hash=fe1949053ea0021b1ac14a6e4646987bf474750fd01e382fa5835b62a4c30b4c
electrumx  | INFO:BlockProcessor:Calculated Atomicals Block Hash: height=817983, atomicals_block_hash=f6615b84fb701b28a9866f84da3e886056b5ca0005b9ed17a3efb8456d930ada
electrumx  | INFO:Prefetcher:cancelled; prefetcher stopping 
electrumx  | INFO:Controller:shutting down
electrumx  | INFO:Controller:shutdown complete
electrumx  | ERROR:electrumx:ElectrumX server terminated abnormally
electrumx  | Traceback (most recent call last):
electrumx  |   File "/electrumx/electrumx_server", line 35, in main
electrumx  |     asyncio.run(controller.run())
electrumx  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
electrumx  |     return loop.run_until_complete(main)
electrumx  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
electrumx  |   File "/electrumx/electrumx/lib/server_base.py", line 129, in run
electrumx  |     await server_task
electrumx  |   File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
electrumx  |     await self.serve(shutdown_event)
electrumx  |   File "/electrumx/electrumx/server/controller.py", line 137, in serve
electrumx  |     await group.spawn(wait_for_catchup())
electrumx  |   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
electrumx  |     await self.join()
electrumx  |   File "/electrumx/electrumx/lib/util.py", line 370, in join
electrumx  |     task.result()
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 3501, in fetch_and_process_blocks
electrumx  |     await group.spawn(self._process_prefetched_blocks())
electrumx  |   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
electrumx  |     await self.join()
electrumx  |   File "/electrumx/electrumx/lib/util.py", line 370, in join
electrumx  |     task.result()
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 3461, in _process_prefetched_blocks
electrumx  |     await self.check_and_advance_blocks(blocks)
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 310, in check_and_advance_blocks
electrumx  |     await self.run_in_thread_with_lock(self.advance_blocks, blocks)
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 293, in run_in_thread_with_lock
electrumx  |     return await asyncio.shield(run_in_thread_locked())
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 292, in run_in_thread_locked
electrumx  |     return await run_in_thread(func, *args)
electrumx  |   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 57, in run_in_thread
electrumx  |     return await get_event_loop().run_in_executor(None, func, *args)
electrumx  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
electrumx  |     result = self.fn(*self.args, **self.kwargs)
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 494, in advance_blocks
electrumx  |     undo_info, atomicals_undo_info = self.advance_txs(block.transactions, is_unspendable, block.header, height)
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 2726, in advance_txs
electrumx  |     cache_value = spend_utxo(txin.prev_hash, txin.prev_idx)
electrumx  |   File "/electrumx/electrumx/server/block_processor.py", line 3444, in spend_utxo
electrumx  |     raise ChainError(f'UTXO {hash_to_hex_str(tx_hash)} / {tx_idx:,d} not '
electrumx  | electrumx.server.block_processor.ChainError: UTXO 59840670e5544a3d0b933bf168e887e28d2a87ff92d11f01690d0e9e5640bb20 / 1 not found in "h" table
```

**Comment by AI-Chef** [comment]
when I upgrade from 1.3.0 to 1.3.1

**Comment by atomicals** [comment]
You need to resync fresh perhaps
