### ISSUE TITLE
Version 1.4.2 does not work

### ISSUE THREAD

**Issue by YuXiaoCoder** [atomicals/atomicals-electrumx#186]
```bash
python3 /opt/atomicalsmain/core/atomicals-electrumx/electrumx_server
```

```log
Traceback (most recent call last):
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx_server", line 19, in <module>
    from electrumx import Controller, Env
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx/__init__.py", line 6, in <module>
    from electrumx.server.env import Env
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx/server/env.py", line 16, in <module>
    from electrumx.lib.coins import Coin, AtomicalsCoinMixin
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx/lib/coins.py", line 49, in <module>
    import electrumx.server.block_processor as block_proc
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx/server/block_processor.py", line 227, in <module>
    class BlockProcessor:
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx/server/block_processor.py", line 2855, in BlockProcessor
    ) -> tuple[list[bytes], list[bytes]]:
TypeError: 'type' object is not subscriptable
```

**Comment by AlexV525** [comment]
What Python version are you using? Could you change `tuple` to `Tuple` to check if it works?

**Comment by YuXiaoCoder** [comment]
My python version is 3.8.10.
![image](https://github.com/atomicals/atomicals-electrumx/assets/26297513/164b6e2d-cc25-437c-b274-3a39b962988a)

**Comment by YuXiaoCoder** [comment]
After I upgraded to Python 3.10.12, which works fine, I'd recommend updating the README.md
