### ISSUE TITLE
spawn() got an unexpected keyword argument 'daemon'

### ISSUE THREAD

**Issue by www222fff** [atomicals/atomicals-electrumx#19]
INFO:Controller:Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dannyaw/blockchain/atomicals-electrumx/electrumx/lib/server_base.py", line 118, in run
    server_task = await spawn(serve, daemon=True)
TypeError: spawn() got an unexpected keyword argument 'daemon'

**Comment by www222fff** [comment]
pip3 install aiorpcx --upgrade to aiorpcx-0.22.1 works well now.
