### ISSUE TITLE
For version 1.5.0.3, the information is not available through the CLI.

### ISSUE THREAD

**Issue by YuXiaoCoder** [atomicals/atomicals-electrumx#223]
Version：1.5.0.3

```bash
/opt/atomicalsmain/core/atomicals-electrumx/electrumx_rpc getinfo
```

The error log is as follows:
```bash
Traceback (most recent call last):
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx_rpc", line 144, in send_request
    result = await session.send_request(method, args)
  File "/usr/local/lib/python3.10/dist-packages/aiorpcx/session.py", line 540, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/usr/local/lib/python3.10/dist-packages/aiorpcx/session.py", line 512, in _send_concurrent
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx_rpc", line 173, in <module>
    main()
  File "/opt/atomicalsmain/core/atomicals-electrumx/electrumx_rpc", line 168, in main
    code = asyncio.run(send_request())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError

Exception in callback _SelectorSocketTransport._call_connection_lost(AttributeErro...ta_received'"))
handle: <Handle _SelectorSocketTransport._call_connection_lost(AttributeErro...ta_received'"))>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 984, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 742, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/usr/local/lib/python3.10/dist-packages/aiorpcx/rawsocket.py", line 91, in connection_lost
    self._framer.fail(ConnectionLostError())
AttributeError: 'NoneType' object has no attribute 'fail'
```

Expect a return message:
```bash
{
    "coin": "Bitcoin",
    "daemon": "btc-0.btc.blocknodehub.com:8332/",
    "daemon height": 849817,
    "db height": 849817,
    "db_flush_count": 3490,
    "groups": 0,
    "history cache": "0 lookups 0 hits 0 entries",
    "merkle cache": "0 lookups 0 hits 0 entries",
    "peers": {
        "bad": 3,
        "good": 121,
        "never": 2,
        "stale": 6,
        "total": 132
    },
    "pid": 1788948,
    "request counts": {
        "blockchain.atomicals.at_location": 6115,
        "blockchain.atomicals.get_global": 20052,
        "blockchain.atomicals.listscripthash": 55,
        "getinfo": 1,
        "server.donation_address": 8251,
        "server.version": 1701
    },
    "request total": 36175,
    "sessions": {
        "count": 2,
        "count with subs": 0,
        "errors": 0,
        "logged": 0,
        "pending requests": 1,
        "subs": 0
    },
    "tx hashes cache": "0 lookups 0 hits 0 entries",
    "txs sent": 0,
    "uptime": "5d 23h 44m",
    "version": "ElectrumX 1.16.0"
}
```

**Comment by wizz-wallet-dev** [comment]
The fix has landed on the `develop` branch.
