### ISSUE TITLE
Error while blockchain.atomicals.get

### ISSUE THREAD

**Issue by disco-quotidie** [atomicals/atomicals-electrumx#225]
I am getting this error from Atomicals-ElectrumX when I call blockchain.atomicals.get function.
It used to work correctly until yesterday.

Jul 03 09:41:12 qs29704 electrumx_server[15159]: ERROR:ElectrumX:[21132] exception handling Request('blockchain.atomicals.get', ['609ca0cabdea8a953914263b6b1b973e630d6204993c99134139580ee7865246i0'])
Jul 03 09:41:12 qs29704 electrumx_server[15159]: Traceback (most recent call last):
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/usr/local/lib/python3.10/dist-packages/aiorpcX-0.23.1-py3.10.egg/aiorpcx/session.py", line 481, in _throttled_request
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     result = await self.handle_request(request)
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/home/electrumx_user/atomicals-electrumx/electrumx/server/session/session_base.py", line 138, in handle_request
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     return await coro
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/home/electrumx_user/atomicals-electrumx/electrumx/server/session/shared_session.py", line 282, in atomicals_get
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     "result": await self._atomical_id_get(compact_atomical_id),
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/home/electrumx_user/atomicals-electrumx/electrumx/server/session/shared_session.py", line 1097, in _atomical_id_get
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     return await self.session_mgr.atomical_id_get(compact_atomical_id)
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/home/electrumx_user/atomicals-electrumx/electrumx/server/session/session_manager.py", line 1187, in atomical_id_get
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     atomical = await self.bp.get_base_mint_info_rpc_format_by_atomical_id(atomical_id)
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/home/electrumx_user/atomicals-electrumx/electrumx/server/block_processor.py", line 2571, in get_base_mint_info_rpc_format_by_atomical_id
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     self.atomicals_rpc_format_cache[atomical_id] = atomical_result
Jul 03 09:41:12 qs29704 electrumx_server[15159]:   File "/usr/local/lib/python3.10/dist-packages/pylru-1.2.1-py3.10.egg/pylru.py", line 140, in __setitem__
Jul 03 09:41:12 qs29704 electrumx_server[15159]:     del self.table[node.key]
Jul 03 09:41:12 qs29704 electrumx_server[15159]: KeyError: b'J8\xf4\xbd\x90\xbe\xd5\xa9\xf9\x8a\xf4\xc3R\x91\xdd\xfa\xaf\x0e\x80\xc0\xe8X\xdd\xcbf\x14\x9f\x0f$\x15q\xa7\x00\x00\x00\x00'
Jul 03 09:41:58 qs29704 electrumx_server[15159]: INFO:MemPool:82,776 txs 60.70 MB touching 341,412 addresses
Jul 03 09:41:58 qs29704 electrumx_server[15159]: INFO:MemPool:compact fee histogram: [(27.0, 32523), (17.7, 35169), (13.4, 36769), (11.1, 41890), (10.4, 44074), (9.4, 60536), (8.4, 77396), (8.3, 63149), (8.1, 87605), (7.9, 79469), (7.3, 156632), (7.0, 144493), (6.9, 113333), (6.7, 15825), (6.6, 2369945), (6.5, 7366999), (6.4, 1729145), (6.3, 1536912), (6.2, 1353531), (6.1, 247909), (6.0, 5895438), (5.8, 486795), (5.6, 406735), (5.4, 253721), (5.3, 774682), (5.2, 1877457), (5.1, 1794043), (5.0, 12971301), (4.9, 365434), (4.8, 1800421), (4.6, 724783), (4.4, 713689), (4.2, 1203532), (4.1, 836598), (4.0, 6759433), (3.8, 840727), (3.7, 4875589), (3.2, 1045969), (3.0, 1308312)]

Can anybody help ?

**Comment by disco-quotidie** [comment]
Seems like my this error happens after running electrumx for a while.
Today it happened again.
I see same error on Electrumx logs.

**Comment by disco-quotidie** [comment]
I tried pip install pylru
but got
Requirement already satisfied: pylru in /usr/local/lib/python3.10/dist-packages/pylru-1.2.1-py3.10.egg (1.2.1)
