### ISSUE TITLE
Error calling blockchain.atomicals.list

### ISSUE THREAD

**Issue by xyunsh** [atomicals/atomicals-electrumx#231]
url: 'http://localhost:8080/proxy/blockchain.atomicals.list',
    data: '{"params":[50,84350,1]}'

```
024-09-27 11:59:50 ERROR:HttpSession:Exception during formatting request: POST http://localhost:8080/proxy/blockchain.atomicals.list, exception: Object of type undefined_type is not JSON serializable, stack: Traceback (most recent call last):
2024-09-27 11:59:50   File "/electrumx/electrumx/server/session/http_session.py", line 69, in formatted_request
2024-09-27 11:59:50     return success_resp(result)
2024-09-27 11:59:50   File "/electrumx/electrumx/server/http_middleware.py", line 100, in success_resp
2024-09-27 11:59:50     return web.json_response(data=result)
2024-09-27 11:59:50   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 811, in json_response
2024-09-27 11:59:50     text = dumps(data)
2024-09-27 11:59:50   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
2024-09-27 11:59:50     return _default_encoder.encode(obj)
2024-09-27 11:59:50   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
2024-09-27 11:59:50     chunks = self.iterencode(o, _one_shot=True)
2024-09-27 11:59:50   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
2024-09-27 11:59:50     return _iterencode(o, 0)
2024-09-27 11:59:50   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
2024-09-27 11:59:50     raise TypeError(f'Object of type {o.__class__.__name__} '
2024-09-27 11:59:50 TypeError: Object of type undefined_type is not JSON serializable
2024-09-27 11:59:50 
```

**Comment by xyunsh** [comment]
https://[ep.nextdao.xyz/proxy/blockchain.atomicals.list?params=[50,84350,1]](https://ep.nextdao.xyz/proxy/blockchain.atomicals.list?params=[50,84350,1])

**Comment by wizz-wallet-dev** [comment]
Which network is serving with?

**Comment by xyunsh** [comment]
Mainnet

**Comment by xyunsh** [comment]
https://[ep.nextdao.xyz/proxy/blockchain.atomicals.list?params=[50,84350,1]](https://ep.nextdao.xyz/proxy/blockchain.atomicals.list?params=%5B50,84350,1%5D)

**Comment by wizz-wallet-dev** [comment]
The cause is `869a5e422e07949728da4ee76b574dd12d2c51d45f2e5a7753f98df787894df8i0`.

https://ep.nextdao.xyz/proxy/blockchain.atomicals.get?params=[%22869a5e422e07949728da4ee76b574dd12d2c51d45f2e5a7753f98df787894df8i0%22]

**Comment by wizz-wallet-dev** [comment]
Update the `auto_encode_bytes_elements` in `electrumx/lib/utils_atomicals.py` can solves the issue:

```diff
# Auto encodes data into structured bytes data.
def auto_encode_bytes_elements(state):
    if isinstance(state, bytes):
        return {"$b": state.hex(), "$len": sys.getsizeof(state), "$auto": True}

    if isinstance(state, CBORTag):
        dumped_bytes = dumps(state)
        return auto_encode_bytes_elements(dumped_bytes)

    if isinstance(state, list):
        reformatted_list = []
        for item in state:
            reformatted_list.append(auto_encode_bytes_elements(item))
        return reformatted_list

    if isinstance(state, dict):
        for key, value in state.items():
            state[key] = auto_encode_bytes_elements(value)

+   # Handles unknown undefined type.
+   if type(state).__name__ == 'undefined_type':
+       return None

    return state
```

**Comment by wizz-wallet-dev** [comment]
https://ep.wizz.cash/proxy/blockchain.atomicals.get?params=%5B%22869a5e422e07949728da4ee76b574dd12d2c51d45f2e5a7753f98df787894df8i0%22%5D

**Comment by Electron2030** [comment]
It would be nice to give some update on Avm's progress to the community 
The block 888888 would be great to see avm released

**Comment by wizz-wallet-dev** [comment]
Fixed in #233.
