### ISSUE TITLE
crash when chain reorg

### ISSUE THREAD

**Issue by yvvw** [atomicals/atomicals-electrumx#49]
version: [v1.3.7.2](https://github.com/atomicals/atomicals-electrumx/releases/tag/v1.3.7.2)

```log
atomicals  | INFO:electrumx:ElectrumX server starting
atomicals  | INFO:electrumx:logging level: INFO
atomicals  | INFO:Controller:Python version: 3.10.11 (main, May  3 2023, 09:48:29) [GCC 11.2.1 20220219]
atomicals  | INFO:Controller:software version: ElectrumX 1.16.0
atomicals  | INFO:Controller:aiorpcX version: 0.22.1
atomicals  | INFO:Controller:supported protocol versions: 1.4-1.4.3
atomicals  | INFO:Controller:event loop policy: <uvloop.EventLoopPolicy object at 0x7fdb98937d60>
atomicals  | INFO:Controller:reorg limit is 200 blocks
atomicals  | INFO:Daemon:daemon #1 at host.docker.internal:8332/ (current)
atomicals  | INFO:DB:switching current directory to /app/data
atomicals  | INFO:DB:using leveldb for DB backend
atomicals  | INFO:DB:opened UTXO DB (for sync: True)
atomicals  | INFO:DB:UTXO DB version: 8
atomicals  | INFO:DB:coin: Bitcoin
atomicals  | INFO:DB:network: mainnet
atomicals  | INFO:DB:height: 823,226
atomicals  | INFO:DB:tip: 0000000000000000000365e705dbbea406f6e383f510d400fa23e40eae71e056
atomicals  | INFO:DB:tx count: 943,688,366
atomicals  | INFO:DB:atomical count: 140,809
atomicals  | INFO:DB:flushing DB cache at 1,200 MB
atomicals  | INFO:History:history DB version: 1
atomicals  | INFO:History:flush count: 4,871
atomicals  | INFO:Prefetcher:catching up to daemon height 823,261 (35 blocks behind)
atomicals  | INFO:BlockProcessor:chain reorg detected
atomicals  | INFO:BlockProcessor:chain was reorganised replacing 1 block at heights 823,226-823,226
atomicals  | INFO:BlockProcessor:read 1 blocks from disk
atomicals  | INFO:BlockProcessor:backup_txs m=5848
atomicals  | INFO:BlockProcessor:atomicals_undo_info_map={}
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 5718 - count 0 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 5718 1669d42e672f376113b09b34f4046d83a9a829fb7d0fe49a48e2f43dd4d8ea0f000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d9200000000ca85d4e89209f9c7477a54c5edffeccbec37a11df7dbe9be3606f551b736055b20a79dc7200afef402fb37e8030000000000000000cf553d3800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 5588 - count 1 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 5588 f1d00c8b690cd6564b5369eecc738476f8e7c2de74d53ee460f50e712fa21ca400000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf025910000000086a3fbbf0fad05291d424ca34809494edc83d4080bd10843b99fe23807e6f0efdc1110e318c182990ca188204e000000000000000030e4373800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 5458 - count 2 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 5458 b3faf1ad79dbbd091e0f50f2997d8535394b166022cccb1873f040e23407c07d000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d9200000000cd9c692d3cbaecaed41e58fcf50aa4d221af3fc26acde07e70f84308c914f69796cf57f43bc95760e8d8f8e8030000000000000000cc573d3800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 5328 - count 3 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 5328 5b006345b98be3c1845b87daca7be56eb9cc2662eeae91acdb87bac1e5e9eba9000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d920000000037442d9a58501754d65c96d05f63ef5fb6f2067395b48a9625a864b67e576a17ff7fcb2916ff4112a07ad6e8030000000000000000c9df3d3800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 5198 - count 4 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 5198 0bd2e7ac0f644d5dc391312b5daa6fff6dfc5d819ee0613f64fe35ffa4dd1cf9000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d92000000005f0b10b75aa092be3bd7fc469e5e54d14d29b34192ea791aa604d819365e5d2d58a47d747cfcc3d359ea2fe803000000000000000039263d3800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 5068 - count 5 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 5068 1551c1d9024b8f2a5e8acd4bcfafdeff6a9ce9a386c8d24c5ffd2f2e4616efe700000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000000d4b65477da43dbd6103706a7644a88803b083e59487073e4761e26e5d9a0a17a093f3e24f185925a2c22d204e0000000000000000b681373800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4938 - count 6 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4938 e0b6dd34acdfafc2e8f52b21a510b4ed946399e43d68b7d00356af5507d2ad8e00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000dd51383800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4808 - count 7 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4808 7c57c97ac5de32cbbb0e4bf836bd26ed6805f33b201884d7497662ceb1297e3800000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e00000000000000000ce5363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4678 - count 8 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4678 fe6d361f5af076cdc4affdd49bb9064e694e5e81f7cce37a733a619c972f897400000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e00000000000000000ae5363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4548 - count 9 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4548 20b0fff7999c15c1c5bb0ffcbc17a4a7e1dc83bf0e05dd3b32f815428fc4b6b800000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000deb9363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4418 - count 10 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4418 4ab46d1f7489c565fbac5d9dc0aadf58cf388dddef00c9c10ea8a9e3cf91cae600000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000dcb9363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4288 - count 11 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4288 a80b8165202ac689833878031a39760191eca50af1aec22acf21271da83178d400000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000dab9363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4158 - count 12 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4158 0ba8b5c2bab22e9e0c5b683b6cae6822cababe2fbf767483d790727a52081ec300000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e00000000000000002dbb363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 4028 - count 13 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 4028 4d9009951ad7264789bb74014b792db1f442580f0fe6fe3a38d891f947f4064b00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e0000000000000000e751363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3898 - count 14 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3898 fbe79d7ba5ce104bfa474bded62ff59ecec9e8a60f7888d047997e483d73127e00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e0000000000000000e144363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3768 - count 15 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3768 ebb6ddf7625336a6557aeb3530e98d604caa4842a401881932296a7ad0fba27a00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e00000000000000007444363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3638 - count 16 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3638 e5262d035a92bd3b264e78954234f8c498d1468818d470d19b9690f928508cb400000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e00000000000000004244363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3508 - count 17 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3508 ce8f4c2a70d048edc3009f70b62394510db602fa5bdb651167f6fc525f85a65200000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e0000000000000000d325363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3378 - count 18 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3378 c4f1874bf18f5fe22c5f6b31c44cda6481cfd0dbf44ef002ac97036fecea271e00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e00000000000000009925363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3248 - count 19 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3248 bf4774bb02f64e9522c61f9e5a16f3abf8e0a09823dbbf1f46688c417cfa98a100000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000a18fbf0f1b383b7d846a778de3d8ea79b7bf2ecd2dc69ab7d92a40a4d2818eefda952dd29151d8a2f8b74a204e00000000000000007425363800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 3118 - count 20 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 3118 76c8fdced9f05bd7207ca1fa60ac53d310cf4afe87ef6dbd925ffd3fd52398a6000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d92000000006c160d5af100be2b124bcde4b6c5db8d577317c72389bb6e6ccb5e49bb608785524595dae0c85b83c94bc4e803000000000000000036b33d3800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2988 - count 21 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2988 4d16de2d17cdffcdde1c7b3c1022a9c7af696dd3b11ee27799572438e97ea0f1000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d920000000098f978c6cbdee7849c972e03ad6629acb4f2d812d629c492ebe58dbd35a917bd5619dcdfad4b2fcbbd59f1e8030000000000000000ac4b3d3800
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2858 - count 22 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2858 380095bb9ee07ed5cbf36090a215457182e06a75f08efbed13b5b2d0eb80302968ab00000000908ee68352516d76f43f00296a6f91141e57e22b34ca3b2317faafdfaa37675300000000750348df7d09137e5ed2051b8061b36f60e74e7d234863b5b0783f89760c6c622c6ea1c7a3688dca4cf1f048d50000000000004b893a3700
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2728 - count 23 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2728 38008c888f847ce2bb87a960b095ef77f6143ecfbcc2fa2df01dae70dd4db9213a560000000041038f27e785606ca0cc1efd8e3aa912a15c72d06f359aeb05243dab2b70a856000000002541d800ca7500b2770a0c0dc18cbbe7acee5d0f3dad1cd915ad30869ae17c5e2ceb75b189b734c0149b5ae80300000000000000000a4b1e
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2598 - count 24 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2598 380013909169dad4f6783c2bce0d0cd518a02b8848f335ebbc90a9042abde4b87be00000000072e64078bf0c8e038f19ed5c3ea70d89a0d3638d7efa080b3295cc0c0482d0b10000000054daa08d503c2c00b9a070827948ae5345d74cb2fdb2250ef138e03d1a79d7664fcb8fa923ecf9474283f5e8030000000000000000337819
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2468 - count 25 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2468 38009478f3365d19f061c6a263d7742fe318d506998af1543977e5f9d6b543b2108400000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000006fdf2836d43b994f3dd524cdf6170e8bf0dfdf9d3cdea54696f3f9360469c8eb08f455f1d3428b5bf92892204e00000000000000005d5536
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2338 - count 26 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2338 38000b3e4860f19eb98c03166dad3e88fdfcfa8c1ec0fcf4f0f76f0df16ddf832a4c00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000006fdf2836d43b994f3dd524cdf6170e8bf0dfdf9d3cdea54696f3f9360469c8eb08f455f1d3428b5bf92892204e00000000000000005b5536
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2208 - count 27 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2208 38006d5146d5ff6099c524a26ede850bdedf20c56e2fcd4af93ca42e54a458ffdc2800000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000006fdf2836d43b994f3dd524cdf6170e8bf0dfdf9d3cdea54696f3f9360469c8eb08f455f1d3428b5bf92892204e00000000000000005c5536
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 2078 - count 28 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 2078 3800ed8b53d36a949f60d8482c1fc24fdd858ea8f63288996168e0a6d56d5b36726600000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e000000000000000097de37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1948 - count 29 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1948 3800ebea12193c790d433c390266d8faf6d850c3c2f9111ac9e3872477f524e3aa3200000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e000000000000000095de37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1818 - count 30 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1818 380003bf9cbd53639c2e768066c201f5d47039d6268d3a0acf0e07e475c29d6be25800000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e000000000000000045de37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1688 - count 31 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1688 38005f1132aaae677c7f2890001916aaa1aa782424959324998143428372600400d700000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e000000000000000043de37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1558 - count 32 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1558 3800d9a07642b919b132f49f14c1b0312e86d03d4a6f3f45d85326bc4575d877618d00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000b22f37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1428 - count 33 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1428 3800dfcb2c7f557c1b48f7515d191be0520f70951792b6c6c42223d952d108651be200000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e00000000000000000c1a37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1298 - count 34 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1298 38007a7529a734d2b03c4918dfcf2f7f4f2bd4545e39a0d3097668b498813cc3689b00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000041a37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1168 - count 35 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1168 3800462044380d013a638d53853e89e33c067ba4603ce6d7f275157aee63b689fba000000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e0000000000000000c00b37
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 1038 - count 36 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 1038 3800df7436b48f5acaed90e51263c092fc79b5ea1f123f57897d63f5bcca1cc0123c00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e000000000000000052f836
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 908 - count 37 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 908 3800662fca5e1bce7704e8fa1375514a11b660e6f4c892bda8968559271c335853b200000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf02591000000002f1aca263336d3976d8a72938866d40400570d3f2c900e412fa87d072adbda03c9d2b1de67d82bcbc58662204e00000000000000004cf836
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 778 - count 38 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 778 380002833dfa23fee4217ccb974318a8700231a24e9e51730a22d8d659566f28098000000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000933aed32c6a0855860b8bc806a1a9f619a7a60ef786262be811c3d76070d2fe200ad6dd0c02d45ee48e1e9204e000000000000000088ee35
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 648 - count 39 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 648 3800870f9189780c39b8931e6f2de878d25abc5090694f608167c397a3e82bdf076a00000000666fea477fe0892e6e337c15ed430b1a460be0aeb9621707f62593cf3bf0259100000000933aed32c6a0855860b8bc806a1a9f619a7a60ef786262be811c3d76070d2fe200ad6dd0c02d45ee48e1e9204e000000000000000086ee35
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 518 - count 40 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 518 3800825582bf860a1649aed3949216ad5121d8c43b8e6bc7f8386f43cfa157d241ab000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d92000000006c160d5af100be2b124bcde4b6c5db8d577317c72389bb6e6ccb5e49bb608785524595dae0c85b83c94bc4e80300000000000000002cc83d
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 388 - count 41 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 388 380057a024864392b5b97b57d99a0a07c0fda0a240340f4d245e34facc828f4db1ea000000009d304417368fdcebf51b7e2d2f5c4b7acbd9013d1e170dbebc7aae7f125f3d9200000000e98683d8186fb180c8b13982f2523bdcf4a6022d8f55291d13f96c293daa945577b4150253aede6187ced6e80300000000000000005e2a3d
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 258 - count 42 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 258 38002c36a372ec221577fef265053c569b7cf6d27ed905fbb3fe6f86f69b5a61e04000000000afdef5feb85029eaf1905e906aef1de6469072155198e1c524d9e8d0855162ab00000000f45e6167f7f9bf343b60966a6e8e5a8a5024f579e9d06d98154736f4d7a17f0c223f576db885a38ef5a7b9166b9f06000000000000656c3f
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len 128 - count 43 - 130
atomicals  | INFO:BlockProcessor:Reorg undo_info_item 128 38002c36a372ec221577fef265053c569b7cf6d27ed905fbb3fe6f86f69b5a61e04000000000794f82c79db8df571134d60a1c135eb555a67701bcc2753b28f7aa1dac8e39ab00000000f45e6167f7f9bf343b60966a6e8e5a8a5024f579e9d06d98154736f4d7a17f0c223f576db885a38ef5a7b9166b9f06000000000000656c3f
atomicals  | INFO:BlockProcessor:atomicals_undo_entry_len -2 - count 44 - 130
atomicals  | INFO:Prefetcher:cancelled; prefetcher stopping
atomicals  | INFO:Controller:shutting down
atomicals  | INFO:Controller:shutdown complete
atomicals  | ERROR:electrumx:ElectrumX server terminated abnormally
atomicals  | Traceback (most recent call last):
atomicals  |   File "/app/electrumx_server", line 35, in main
atomicals  |     asyncio.run(controller.run())
atomicals  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
atomicals  |     return loop.run_until_complete(main)
atomicals  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
atomicals  |   File "/app/electrumx/lib/server_base.py", line 129, in run
atomicals  |     await server_task
atomicals  |   File "/app/electrumx/lib/server_base.py", line 102, in serve
atomicals  |     await self.serve(shutdown_event)
atomicals  |   File "/app/electrumx/server/controller.py", line 134, in serve
atomicals  |     async with OldTaskGroup() as group:
atomicals  |   File "/usr/local/lib/python3.10/site-packages/aiorpcx/curio.py", line 297, in __aexit__
atomicals  |     await self.join()
atomicals  |   File "/app/electrumx/lib/util.py", line 370, in join
atomicals  |     task.result()
atomicals  |   File "/app/electrumx/server/block_processor.py", line 3580, in fetch_and_process_blocks
atomicals  |     async with OldTaskGroup() as group:
atomicals  |   File "/usr/local/lib/python3.10/site-packages/aiorpcx/curio.py", line 297, in __aexit__
atomicals  |     await self.join()
atomicals  |   File "/app/electrumx/lib/util.py", line 370, in join
atomicals  |     task.result()
atomicals  |   File "/app/electrumx/server/block_processor.py", line 3542, in _process_prefetched_blocks
atomicals  |     await self.check_and_advance_blocks(blocks)
atomicals  |   File "/app/electrumx/server/block_processor.py", line 323, in check_and_advance_blocks
atomicals  |     await self.reorg_chain()
atomicals  |   File "/app/electrumx/server/block_processor.py", line 365, in reorg_chain
atomicals  |     await self.run_in_thread_with_lock(self.backup_blocks, raw_blocks)
atomicals  |   File "/app/electrumx/server/block_processor.py", line 295, in run_in_thread_with_lock
atomicals  |     return await asyncio.shield(run_in_thread_locked())
atomicals  |   File "/app/electrumx/server/block_processor.py", line 294, in run_in_thread_locked
atomicals  |     return await run_in_thread(func, *args)
atomicals  |   File "/usr/local/lib/python3.10/site-packages/aiorpcx/curio.py", line 57, in run_in_thread
atomicals  |     return await get_event_loop().run_in_executor(None, func, *args)
atomicals  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
atomicals  |     result = self.fn(*self.args, **self.kwargs)
atomicals  |   File "/app/electrumx/server/block_processor.py", line 3130, in backup_blocks
atomicals  |     self.backup_txs(block.transactions, is_unspendable)
atomicals  |   File "/app/electrumx/server/block_processor.py", line 3303, in backup_txs
atomicals  |     assert(c >= 0)
atomicals  | AssertionError
atomicals exited with code 0
```

**Comment by joepeak** [comment]
me too,do you solve is?

**Comment by yvvw** [comment]
no, it look like undo entry length is not match exactly. is there any rollback way? i don't want to resync again.

**Comment by yvvw** [comment]
i have re-synchronized the node. REMEMBER take snapshot periodic.

**Comment by joepeak** [comment]
ok, thanks

**Comment by atomicals** [comment]
We will identify the underlying problem soon.
