### ISSUE TITLE
rockdb install failure in dockerfile

### ISSUE THREAD

**Issue by lcgogo** [atomicals/atomicals-electrumx#63]
According to https://github.com/atomicals/atomicals-electrumx/blob/master/contrib/Dockerfile

When build the image
docker build -t electrumx .

printout followed error
```
      rocksdb/_rocksdb.pyx:2413:44: Converting to Python object not allowed without gil
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b3qywp9c/python-rocksdb_426e6e6d47a4476cbec9cba46b9b4cf5/setup.py", line 21, in <module>
          setup(
        File "/usr/src/app/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/src/app/venv/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.9/distutils/command/install.py", line 546, in run
          self.run_command('build')
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/src/app/venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/local/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/usr/local/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/usr/local/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/usr/src/app/venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-install-b3qywp9c/python-rocksdb_426e6e6d47a4476cbec9cba46b9b4cf5/.eggs/Cython-3.0.7-py3.9-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 130, in build_extension
          new_ext = cythonize(
        File "/tmp/pip-install-b3qywp9c/python-rocksdb_426e6e6d47a4476cbec9cba46b9b4cf5/.eggs/Cython-3.0.7-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-install-b3qywp9c/python-rocksdb_426e6e6d47a4476cbec9cba46b9b4cf5/.eggs/Cython-3.0.7-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: rocksdb/_rocksdb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-rocksdb

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

@GoodDaisy  Please help.

**Comment by lucky2077** [comment]
I've tried rocksdb, it's not working by now. Use leveldb. You can also refer to:

https://github.com/Next-DAO/atomicals-electrumx-docker/blob/main/Dockerfile

**Comment by AlexV525** [comment]
https://github.com/atomicals/atomicals-electrumx/pull/152 enables the ability to use RocksDB.
