### ISSUE TITLE
plyvel._plyvel.CorruptionError: b'Corruption: corrupted compressed block contents'

### ISSUE THREAD

**Issue by Redamancyer** [atomicals/atomicals-electrumx#65]
Traceback (most recent call last):
  File "electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/Users/admin/miniconda3/envs/atom/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/admin/miniconda3/envs/atom/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/lib/server_base.py", line 129, in run
    await server_task
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/lib/server_base.py", line 102, in serve
    await self.serve(shutdown_event)
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/controller.py", line 137, in serve
    await group.spawn(wait_for_catchup())
  File "/Users/admin/miniconda3/envs/atom/lib/python3.8/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/block_processor.py", line 3646, in fetch_and_process_blocks
    await self._first_open_dbs()
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/block_processor.py", line 3625, in _first_open_dbs
    await self.db.open_for_sync()
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/db.py", line 360, in open_for_sync
    await self._open_dbs(True, False)
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/db.py", line 337, in _open_dbs
    self.utxo_flush_count = self.history.open_db(self.db_class, for_sync,
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/history.py", line 61, in open_db
    self.read_state()
  File "/Volumes/2TB/Atomicals/atomicals-electrumx-1.3.7.5/electrumx/server/history.py", line 75, in read_state
    state = self.db.get(b'state\0\0')
  File "plyvel/_plyvel.pyx", line 310, in plyvel._plyvel.DB.get
  File "plyvel/_plyvel.pyx", line 111, in plyvel._plyvel.db_get
  File "plyvel/_plyvel.pyx", line 91, in plyvel._plyvel.raise_for_status
plyvel._plyvel.CorruptionError: b'Corruption: corrupted compressed block contents'

**Comment by Redamancyer** [comment]
i use the last data which same as my friends,but always bug,i have try times on macos

**Comment by thejoven** [comment]
same situation

**Comment by xyz-ass** [comment]
same situation

**Comment by AlexV525** [comment]
Please update and retry.
