### ISSUE TITLE
ERROR when try to run atomicals-electrumx with Bitcoin testnet.

### ISSUE THREAD

**Issue by inkjake** [atomicals/atomicals-electrumx#69]
```
ERROR:Prefetcher:ignoring unexpected exception
Traceback (most recent call last):
  File "/electrumx/electrumx/server/block_processor.py", line 128, in main_loop
    if not await self._prefetch_blocks():
  File "/electrumx/electrumx/server/block_processor.py", line 198, in _prefetch_blocks
    blocks[0] = self.coin.genesis_block(blocks[0])
  File "/electrumx/electrumx/lib/coins.py", line 166, in genesis_block
    raise CoinError(f'genesis block has hash {header_hex_hash} '
electrumx.lib.coins.CoinError: genesis block has hash 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943 expected 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
```

Anyone knows how to make it work?

**Comment by inkjake** [comment]
Resolved by checking the code. Thanks.
