### ISSUE TITLE
UnicodeEncodeError crashing the server without a flush.

### ISSUE THREAD

**Issue by LexCutch** [atomicals/atomicals-electrumx#8]
My current bets at the issue are either versioning of some python tools or a locale issue.
I feel most of you are running Ubuntu, and this is from a Debian machine.
```
INFO:BlockProcessor:advance_txs: atomicals_operations_found_at_inputs operation_found=dft, operation_inp
ut_index=0, size_payload=140, tx_hash=d7d3d7142f3e6ff4e392c0561a53717b06fb30de1fdc07979c4645f32847950c,
commit_txid=61452c69a23ae99c669cfd86447d8e8945a5dc7eec582f05c7d4a9231b226929, commit_index=0, reveal_loc
ation_txid=d7d3d7142f3e6ff4e392c0561a53717b06fb30de1fdc07979c4645f32847950c, reveal_location_index=0
INFO:Prefetcher:cancelled; prefetcher stopping
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/home/atom/code/atomicals-electrumx/./electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/atom/code/atomicals-electrumx/electrumx/lib/server_base.py", line 129, in run
    await server_task
  File "/home/atom/code/atomicals-electrumx/electrumx/lib/server_base.py", line 102, in serve
    await self.serve(shutdown_event)
  File "/home/atom/code/atomicals-electrumx/electrumx/server/controller.py", line 137, in serve
    await group.spawn(wait_for_catchup())
  File "/home/atom/.local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/home/atom/code/atomicals-electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 3402, in fetch_an
d_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/home/atom/.local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/home/atom/code/atomicals-electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 3362, in _process
_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 308, in check_and
_advance_blocks
    await self.run_in_thread_with_lock(self.advance_blocks, blocks)
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 291, in run_in_th
read_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 290, in run_in_th
read_locked
    return await run_in_thread(func, *args)
  File "/home/atom/.local/lib/python3.9/site-packages/aiorpcx/curio.py", line 57, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 492, in advance_b
locks
    undo_info, atomicals_undo_info = self.advance_txs(block.transactions, is_unspendable, block.header,
height)
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 2704, in advance_
txs
    created_atomical_id = self.create_or_delete_atomical(atomicals_operations_found_at_inputs, atomicals
_spent_at_inputs, header, height, tx_num, atomical_num, tx, tx_hash, False)
  File "/home/atom/code/atomicals-electrumx/electrumx/server/block_processor.py", line 1241, in create_o
r_delete_atomical
    valid_create_op_type, mint_info = get_mint_info_op_factory(self.coin, tx, tx_hash, operations_found_
at_inputs, atomicals_spent_at_inputs)
  File "/home/atom/code/atomicals-electrumx/electrumx/lib/util_atomicals.py", line 665, in get_mint_info
_op_factory
    print(f'DFT mint has invalid ticker {tx_hash}, {ticker}. Skipping...')
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001d54f' in position 125: ordinal not in
range(256)
```

**Comment by LexCutch** [comment]
Well, it is a locale issue.
A quick fix is to run python with 
```
-X utf8
```

I'll let you decide if its necessary to make sure a flush happens,
because right now this error terminated the server abnormally.

**Comment by AlexV525** [comment]
Someone with the same issue can search and find your solution eventually. Thanks for the report!
