### ISSUE TITLE
 KeyError: '$request_subrealm'

### ISSUE THREAD

**Issue by flex-alcove** [atomicals/atomicals-electrumx#9]
Testnet crash

```
 ERROR:electrumx:ElectrumX server terminated abnormally
 Traceback (most recent call last):
   File "/usr/local/bin/electrumx_server", line 35, in main
     asyncio.run(controller.run())
   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
     return loop.run_until_complete(main)
   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
     return future.result()
   File "/usr/local/lib/python3.10/dist-packages/electrumx/lib/server_base.py", line 129, in run
     await server_task
   File "/usr/local/lib/python3.10/dist-packages/electrumx/lib/server_base.py", line 102, in serve
     await self.serve(shutdown_event)
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/controller.py", line 134, in serve
     async with OldTaskGroup() as group:
   File "/usr/local/lib/python3.10/dist-packages/aiorpcx/curio.py", line 297, in __aexit__
     await self.join()
   File "/usr/local/lib/python3.10/dist-packages/electrumx/lib/util.py", line 370, in join
     task.result()
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 3400, in fetch_and_process_blocks
     async with OldTaskGroup() as group:
   File "/usr/local/lib/python3.10/dist-packages/aiorpcx/curio.py", line 297, in __aexit__
     await self.join()
   File "/usr/local/lib/python3.10/dist-packages/electrumx/lib/util.py", line 370, in join
     task.result()
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 3362, in _process_prefetched_blocks
     await self.check_and_advance_blocks(blocks)
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 308, in check_and_advance_blocks
     await self.run_in_thread_with_lock(self.advance_blocks, blocks)
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 291, in run_in_thread_with_lock
     return await asyncio.shield(run_in_thread_locked())
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 290, in run_in_thread_locked
     return await run_in_thread(func, *args)
   File "/usr/local/lib/python3.10/dist-packages/aiorpcx/curio.py", line 57, in run_in_thread
     return await get_event_loop().run_in_executor(None, func, *args)
   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
     result = self.fn(*self.args, **self.kwargs)
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 492, in advance_blocks
     undo_info, atomicals_undo_info = self.advance_txs(block.transactions, is_unspendable, block.header, height)
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 2721, in advance_txs
     if self.create_or_delete_subrealm_payment_output_if_valid(tx_hash, tx, tx_num, height, atomicals_spent_at_inputs):
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 2780, in create_or_delete_subrealm_payment_output_if_valid
     matched_price_point, parent_realm_id, request_subrealm_name = self.get_expected_subrealm_payment_info(found_atomical_id_for_potential_subrealm, height)
   File "/usr/local/lib/python3.10/dist-packages/electrumx/server/block_processor.py", line 592, in get_expected_subrealm_payment_info
     request_subrealm = found_atomical_mint_info_for_potential_subrealm['$request_subrealm']
 KeyError: '$request_subrealm'
```

**Comment by AlexV525** [comment]
Please submit new issues with a precise block height/atomical id that would reproduce the issue using the latest code.
